# Generated by Django 3.0.5 on 2020-05-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='Payment',
            field=models.CharField(default='', max_length=128),
        ),
    ]
