# Generated by Django 3.0.5 on 2020-05-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rent_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_Name', models.CharField(default='', max_length=128)),
                ('L_Name', models.CharField(default='', max_length=128)),
                ('Phone', models.IntegerField(default='')),
                ('Payment', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='rent',
            name='Payment',
        ),
    ]
