# Generated by Django 3.0.5 on 2020-05-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200521_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Movie_Trailer',
            field=models.URLField(default='', max_length=300),
        ),
    ]
